# Abbreviations available only in interactive shells
status --is-interactive; or exit

# git abbreviations
if type -q git
  abbr -a gco "git checkout"
  abbr -a lz "lazygit"
end

# kubectl abbreviations
if type -q kubectl
  # base kubectl
  abbr -a k "kubectl"
  abbr -a kga "kubectl get all"
  abbr -a kgra "kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found"
  abbr -a krt "kubectl run toolbox -i --tty --rm --restart=Never --image=wwmoraes/toolbox"
  abbr -a kl "kubectl logs"
  abbr -a kpf "kubectl port-forward"
  abbr -a kctx "kubectl ctx"
  abbr -a kns "kubectl ns"
  abbr -a ksh "kubectl get pods | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I% bash -c '</dev/tty kubectl iexec %'"
  abbr -a kosvc "kubectl get services | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs kubectl open-svc"
  abbr -a kgextsvc "kubectl get services | awk '\$5 !~ /<none>/ {\$7=\"\";print}' | column -t"
  abbr -a kgaextsvc "kubectl get services -A | awk '\$5 !~ /<none>/ {\$7=\"\";print}' | column -t"
  # base kubectl (fuzzy)
  abbr -a klf "kubectl get pods | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl logs {}"
  abbr -a kpfpo "kubectl get pods | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl port-forward pod/{} 8080:80"
  abbr -a kpfsvc "kubectl get services | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl port-forward service/{} 8080:80"
  abbr -a kpfing "kubectl get ingresses | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl port-forward ingress/{} 8080:80"
  # k get ...
  abbr -a kgpo "kubectl get pods"
  abbr -a kging "kubectl get ingresses"
  abbr -a kgsvc "kubectl get services"
  abbr -a kgcm "kubectl get configmaps"
  abbr -a kgs "kubectl get secrets"
  abbr -a kgds "kubectl get daemonsets"
  abbr -a kgd "kubectl get deployments"
  abbr -a kgpv "kubectl get persistentvolumes"
  abbr -a kgpvc "kubectl get persistentvolumeclaims"
  abbr -a kgsa "kubectl get serviceaccounts"
  abbr -a kgns "kubectl get namespaces"
  abbr -a kgno "kubectl get nodes"
  abbr -a kgcrd "kubectl get customresourcedefinitions"
  abbr -a kgsts "kubectl get statefulsets"
  abbr -a kghpa "kubectl get horizontalpodautoscalers"
  abbr -a kgcj "kubectl get cronjobs"
  abbr -a kgj "kubectl get jobs"
  abbr -a kgnetpol "kubectl get networkpolicies"
  abbr -a kgr "kubectl get roles"
  abbr -a kgrb "kubectl get rolebindings"
  abbr -a kgcr "kubectl get clusterroles"
  abbr -a kgcrb "kubectl get clusterrolebindings"
  abbr -a kgsc "kubectl get storageclasses"
  abbr -a kgrs "kubectl get replicasets"
  # k get ... (yaml)
  abbr -a kgpoy "kubectl get pods -o yaml"
  abbr -a kgingy "kubectl get ingresses -o yaml"
  abbr -a kgsvcy "kubectl get services -o yaml"
  abbr -a kgcmy "kubectl get configmaps -o yaml"
  abbr -a kgsy "kubectl get secrets -o yaml"
  abbr -a kgdsy "kubectl get daemonsets -o yaml"
  abbr -a kgdy "kubectl get deployments -o yaml"
  abbr -a kgpvy "kubectl get persistentvolumes -o yaml"
  abbr -a kgpvcy "kubectl get persistentvolumeclaims -o yaml"
  abbr -a kgsay "kubectl get serviceaccounts -o yaml"
  abbr -a kgnsy "kubectl get namespaces -o yaml"
  abbr -a kgnoy "kubectl get nodes -o yaml"
  abbr -a kgcrdy "kubectl get customresourcedefinitions -o yaml"
  abbr -a kgstsy "kubectl get statefulsets -o yaml"
  abbr -a kghpay "kubectl get horizontalpodautoscalers -o yaml"
  abbr -a kgcjy "kubectl get cronjobs -o yaml"
  abbr -a kgjy "kubectl get jobs -o yaml"
  abbr -a kgnetpoly "kubectl get networkpolicies -o yaml"
  abbr -a kgry "kubectl get roles -o yaml"
  abbr -a kgrby "kubectl get rolebindings -o yaml"
  abbr -a kgcry "kubectl get clusterroles -o yaml"
  abbr -a kgcrby "kubectl get clusterrolebindings -o yaml"
  abbr -a kgscy "kubectl get storageclasses -o yaml"
  abbr -a kgrsy "kubectl get replicasets -o yaml"
  # k get ... (yaml, fuzzy, neat)
  abbr -a kgpof "kubectl get pods | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat pod {} -o yaml"
  abbr -a kgingf "kubectl get ingress | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat ingress {} -o yaml"
  abbr -a kgsvcf "kubectl get services | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat service {} -o yaml"
  abbr -a kgcmf "kubectl get configmaps | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl get configmap {} -o yaml"
  abbr -a kgsf "kubectl get secrets | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl get secret {} -o yaml"
  abbr -a kgdsf "kubectl get daemonsets | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat daemonset {} -o yaml"
  abbr -a kgdf "kubectl get deployments | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat deployment {} -o yaml"
  abbr -a kgpvf "kubectl get persistentvolumes | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat persistentvolume {} -o yaml"
  abbr -a kgpvcf "kubectl get persistentvolumeclaims | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat persistentvolumeclaim {} -o yaml"
  abbr -a kgsaf "kubectl get serviceaccounts | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat serviceaccount {} -o yaml"
  abbr -a kgnsf "kubectl get namespaces | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat namespace {} -o yaml"
  abbr -a kgnof "kubectl get nodes | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat node {} -o yaml"
  abbr -a kgcrdf "kubectl get customresourcedefinitions | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat customresourcedefinition {} -o yaml"
  abbr -a kgstsf "kubectl get statefulsets | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat statefulset {} -o yaml"
  abbr -a kghpaf "kubectl get horizontalpodautoscalers | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat horizontalpodautoscaler {} -o yaml"
  abbr -a kgcjf "kubectl get cronjobs | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat cronjob {} -o yaml"
  abbr -a kgjf "kubectl get jobs | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat job {} -o yaml"
  abbr -a kgnetpolf "kubectl get networkpolicies | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat networkpolicy {} -o yaml"
  abbr -a kgrf "kubectl get roles | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat role {} -o yaml"
  abbr -a kgrbf "kubectl get rolebindings | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat rolebinding {} -o yaml"
  abbr -a kgcrf "kubectl get clusterroles | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl get clusterrole {} -o yaml"
  abbr -a kgcrbf "kubectl get clusterrolebindings | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat clusterrolebinding {} -o yaml"
  abbr -a kgscf "kubectl get storageclasses | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat storageclass {} -o yaml"
  abbr -a kgrsf "kubectl get replicasets | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl neat replicaset {} -o yaml"
  # k describe ... (non-fuzzy)
  abbr -a kdpo "kubectl describe pods"
  abbr -a kding "kubectl describe ingresses"
  abbr -a kdsvc "kubectl describe services"
  abbr -a kdcm "kubectl describe configmaps"
  abbr -a kds "kubectl describe secrets"
  abbr -a kdds "kubectl describe daemonsets"
  abbr -a kdd "kubectl describe deployments"
  abbr -a kdpv "kubectl describe persistentvolumes"
  abbr -a kdpvc "kubectl describe persistentvolumeclaims"
  abbr -a kdsa "kubectl describe serviceaccounts"
  abbr -a kdns "kubectl describe namespaces"
  abbr -a kdno "kubectl describe nodes"
  abbr -a kdcrd "kubectl describe customresourcedefinitions"
  abbr -a kdsts "kubectl describe statefulsets"
  abbr -a kdhpa "kubectl describe horizontalpodautoscalers"
  abbr -a kdcj "kubectl describe cronjobs"
  abbr -a kdj "kubectl describe jobs"
  abbr -a kdnetpol "kubectl describe networkpolicies"
  abbr -a kdr "kubectl describe roles"
  abbr -a kdrb "kubectl describe rolebindings"
  abbr -a kdcr "kubectl describe clusterroles"
  abbr -a kdcrb "kubectl describe clusterrolebindings"
  abbr -a kdsc "kubectl describe storageclasses"
  abbr -a kdrs "kubectl describe replicasets"
  # k describe ... (fuzzy)
  abbr -a kdpof "kubectl get pods | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe pod {}"
  abbr -a kdingf "kubectl get ingress | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe ingress {}"
  abbr -a kdsvcf "kubectl get services | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe service {}"
  abbr -a kdcmf "kubectl get configmaps | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe configmap {}"
  abbr -a kdsf "kubectl get secrets | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe secret {}"
  abbr -a kddsf "kubectl get daemonsets | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe daemonset {}"
  abbr -a kddf "kubectl get deployments | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe deployment {}"
  abbr -a kdpvf "kubectl get persistentvolumes | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe persistentvolume {}"
  abbr -a kdpvcf "kubectl get persistentvolumeclaims | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe persistentvolumeclaim {}"
  abbr -a kdsaf "kubectl get serviceaccounts | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe serviceaccount {}"
  abbr -a kdnsf "kubectl get namespaces | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe namespace {}"
  abbr -a kdnof "kubectl get nodes | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe node {}"
  abbr -a kdcrdf "kubectl get customresourcedefinitions | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe customresourcedefinition {}"
  abbr -a kdstsf "kubectl get statefulsets | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe statefulset {}"
  abbr -a kdhpaf "kubectl get horizontalpodautoscalers | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe horizontalpodautoscaler {}"
  abbr -a kdcjf "kubectl get cronjobs | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe cronjob {}"
  abbr -a kdjf "kubectl get jobs | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe job {}"
  abbr -a kdnetpolf "kubectl get networkpolicies | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe networkpolicy {}"
  abbr -a kdrf "kubectl get roles | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe role {}"
  abbr -a kdrbf "kubectl get rolebindings | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe rolebinding {}"
  abbr -a kdcrf "kubectl get clusterroles | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe clusterrole {}"
  abbr -a kdcrbf "kubectl get clusterrolebindings | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe clusterrolebinding {}"
  abbr -a kdscf "kubectl get storageclasses | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe storageclass {}"
  abbr -a kdrsf "kubectl get replicasets | fzf --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl describe replicaset {}"
  # k delete ... (fuzzy)
  abbr -a kdelpof "kubectl get pods | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete pod {}"
  abbr -a kdelingf "kubectl get ingress | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete ingress {}"
  abbr -a kdelsvcf "kubectl get services | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete service {}"
  abbr -a kdelcmf "kubectl get configmaps | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete configmap {}"
  abbr -a kdelsf "kubectl get secrets | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete secret {}"
  abbr -a kdeldsf "kubectl get daemonsets | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete daemonset {}"
  abbr -a kdeldf "kubectl get deployments | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete deployment {}"
  abbr -a kdelpvf "kubectl get persistentvolumes | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete persistentvolume {}"
  abbr -a kdelpvcf "kubectl get persistentvolumeclaims | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete persistentvolumeclaim {}"
  abbr -a kdelsaf "kubectl get serviceaccounts | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete serviceaccount {}"
  abbr -a kdelnsf "kubectl get namespaces | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete namespace {}"
  abbr -a kdelnof "kubectl get nodes | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete node {}"
  abbr -a kdelcrdf "kubectl get customresourcedefinitions | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete customresourcedefinition {}"
  abbr -a kdelstsf "kubectl get statefulsets | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete statefulset {}"
  abbr -a kdelhpaf "kubectl get horizontalpodautoscalers | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete horizontalpodautoscaler {}"
  abbr -a kdelcjf "kubectl get cronjobs | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete cronjob {}"
  abbr -a kdeljf "kubectl get jobs | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete job {}"
  abbr -a kdelnetpolf "kubectl get networkpolicies | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete networkpolicy {}"
  abbr -a kdelrf "kubectl get roles | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete role {}"
  abbr -a kdelrbf "kubectl get rolebindings | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete rolebinding {}"
  abbr -a kdelcrf "kubectl get clusterroles | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete clusterrole {}"
  abbr -a kdelcrbf "kubectl get clusterrolebindings | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete clusterrolebinding {}"
  abbr -a kdelscf "kubectl get storageclasses | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete storageclass {}"
  abbr -a kdelrsf "kubectl get replicasets | fzf -m --ansi --header-lines=1 | awk '{print \$1}' | xargs -I{} kubectl delete replicaset {}"
  # work-only abbreviations
  if isWork
    abbr -a kinpr-backends "kubectl ingress-nginx -n nginx-private backends --deployment nginx-private-nginx-ingress-controller"
    abbr -a kinpu-backends "kubectl ingress-nginx -n nginx-public backends --deployment nginx-public-nginx-ingress-controller"

    abbr -a kinpr-certs "kubectl get ingresses -A | awk '{print $1,$2,$3}' | column -t | fzf --header-lines=1 | awk '{print $3}' | tr ',' '\n' | fzf --header='HOST' -1 -0 | xargs kubectl ingress-nginx -n nginx-private certs --deployment nginx-private-nginx-ingress-controller --host"
    abbr -a kinpu-certs "kubectl get ingresses -A | awk '{print $1,$2,$3}' | column -t | fzf --header-lines=1 | awk '{print $3}' | tr ',' '\n' | fzf --header='HOST' -1 -0 | xargs kubectl ingress-nginx -n nginx-public certs --deployment nginx-public-nginx-ingress-controller --host"

    abbr -a kinpr-conf "kubectl ingress-nginx -n nginx-private conf --deployment nginx-private-nginx-ingress-controller"
    abbr -a kinpu-conf "kubectl ingress-nginx -n nginx-public conf --deployment nginx-public-nginx-ingress-controller"

    abbr -a "kinpr-exec" "kubectl ingress-nginx -n nginx-private exec --deployment nginx-private-nginx-ingress-controller"
    abbr -a "kinpu-exec" "kubectl ingress-nginx -n nginx-public exec --deployment nginx-public-nginx-ingress-controller"

    abbr -a kinpr-general "kubectl ingress-nginx -n nginx-private general --deployment nginx-private-nginx-ingress-controller"
    abbr -a kinpu-general "kubectl ingress-nginx -n nginx-public general --deployment nginx-public-nginx-ingress-controller"

    abbr -a kinpr-info "kubectl ingress-nginx -n nginx-private info --service nginx-private-nginx-ingress-controller"
    abbr -a kinpu-info "kubectl ingress-nginx -n nginx-public info --service nginx-public-nginx-ingress-controller"

    # TODO ingresses

    # TODO lint

    abbr -a kinprl "kubectl ingress-nginx -n nginx-private logs --deployment nginx-private-nginx-ingress-controller"
    abbr -a kinpul "kubectl ingress-nginx -n nginx-public logs --deployment nginx-public-nginx-ingress-controller"

    abbr -a kinprs "kubectl ingress-nginx -n nginx-private ssh --deployment nginx-private-nginx-ingress-controller"
    abbr -a kinpus "kubectl ingress-nginx -n nginx-public ssh --deployment nginx-public-nginx-ingress-controller"
  end
end
